### ISSUE TITLE
unpack_chunk no longer works due to changes in packed array structure

### ISSUE THREAD

**Issue by wgaylord** [barneygale/quarry#100]
The way packed arrays worked has changed which is currently breaking unpack_chunk.

**Comment by wgaylord** [comment]
I managed to write a version that works for me for now. So there's no hurry.  Just wasn't sure if you knew.

**Comment by Combustible** [comment]
Any chance you'd be up for pasting some code @wgaylord ? Even a hacky workaround would be valuable to us as well :)

**Comment by wgaylord** [comment]
https://gist.github.com/wgaylord/ff7ff3d3f328f553586c10109c17ff1d I use this.

**Comment by barneygale** [comment]
Sorry for the delay on this one! I did all sorts of "clever" things in the previous implementation that no longer apply. Think I've got the implementation mostly there, just updating tests now!

**Comment by wgaylord** [comment]
No need to be sorry.

**Comment by barneygale** [comment]
Fix is in `master` if anyone wants to give it a spin. One test is broken.

The change breaks support for chunk data from 1.15 and below; it's too complicated and slow to support both formats. On the plus side, the implementation is a little simpler and has greater potential for optimization.

**Comment by wgaylord** [comment]
I will take a look at it today and see if it works out. :)

**Comment by barneygale** [comment]
Closing this issue as I believe things are working! Let me know if you spot problems.
