### ISSUE TITLE
1.16.4 protocol is not actually supported

### ISSUE THREAD

**Issue by TheManchineel** [barneygale/quarry#105]
I'm using the example ["Downtime Server"](https://quarry.readthedocs.io/en/latest/examples.html#downtime-server) script from the documentation. 1.16.3 shows the server perfectly while an incoming 1.16.4 ping causes the server to throw an exception: `ProtocolError("No name known for packet: %s" % (key,))`. I also can't join the server from 1.16.4 ("Unknown protocol version"), while 1.16.3 shows the MOTD kick correctly.

![image](https://user-images.githubusercontent.com/37479927/103134017-3f964a80-46ae-11eb-900c-e73e1b31ab61.png)

**Comment by MsMaciek123** [comment]
If you installed it from pip, then remove it and download version from github. Unpack and open there cmd, and run:
python setup.py build
python setup.py install

You might need to run cmd as administrator

**Comment by dries007** [comment]
Fixed with new release.
