### ISSUE TITLE
Version independent server pinging

### ISSUE THREAD

**Issue by Geolykt** [barneygale/quarry#107]
I've been looking into an issue I have with a project in that if I try to ping the server with a new client protocol version the server will refuse the server list ping and raise an error, which isn't the nicest thing that could be done since that part of the protocol did not change in over 6 years. Is there any way this can be avoided in a sane manner?

More context: https://github.com/mcpyproject/McPy/issues/50 (kind-of outdated but the point still stands)

**Comment by dries007** [comment]
Kind of.
I have thought about implementing something that would try to use the
latest previously known version.
It would be good for supporting minor things, but is liable to cause more
issues than it solves. So it would not be the default.
Can't you handle this on your implementation side?

Op di 26 jan. 2021 23:27 schreef Geolykt <notifications@github.com>:

**Comment by Geolykt** [comment]
Yeah, turns out I was a bit too tired yesterday as I can override the two methods that create the issue rather easily in the protocol implementation
