### ISSUE TITLE
[Feature Request]: Mojang Auth Isn't The Only Way To Log In

### ISSUE THREAD

**Issue by alexis-evelyn** [barneygale/quarry#123]

**Comment by dries007** [comment]
If anyone has documentation on how the MS login works, we might be able to implement this.
Since I only use the server aspect of this project, it's unlikely that I'll be able to help much here.

**Comment by leopoldhub** [comment]
https://mojang-api-docs.netlify.app/authentication/msa.html there is certainly other documentations online

**Comment by folkertvanheusden** [comment]
I also read that starting March (10th iirc) one can only use microsoft accounts for minecraft.

**Comment by koliwbr** [comment]
https://github.com/Wurst-Imperium/Wurst7/blob/master/src/main/java/net/wurstclient/altmanager/MicrosoftLoginManager.java

In Haked client Wurst is Microsoft Auth. Its in java but it work with Microsoft Account. mayby try to revrite to python?

**Comment by leopoldhub** [comment]
> https://github.com/Wurst-Imperium/Wurst7/blob/master/src/main/java/net/wurstclient/altmanager/MicrosoftLoginManager.java
> 
> In Haked client Wurst is Microsoft Auth. Its in java but it work with Microsoft Account. mayby try to revrite to python?

Thanks for the info, I will definitely rewrite it in JavaScript

**Comment by koliwbr** [comment]
> > https://github.com/Wurst-Imperium/Wurst7/blob/master/src/main/java/net/wurstclient/altmanager/MicrosoftLoginManager.java
> > 
> > In Haked client Wurst is Microsoft Auth. Its in java but it work with Microsoft Account. mayby try to revrite to python?
> 
> Thanks for the info, I will definitely rewrite it in JavaScript

I'm in ⅓ rewriting it in *Python*

**Comment by leopoldhub** [comment]
> @leopoldhub You know that this library is a **PYTHON** library. It will not help by rewriting it in **JAVASCRIPT**

@ANDREI12333 Well it will if someone needs to write a **JAVASCRIPT** and not a **PYTHON** app...
