### ISSUE TITLE
Problem with version

### ISSUE THREAD

**Issue by GGuPP1234567890** [barneygale/quarry#126]
Good day, how can I manage versions?
I am trying to connect to a test server with Bungeecord on version 1.12.2 and it keeps giving me an error 

Kicked: Kicked whilst connecting to lobby: Outdated server! I'm still on 1.12.2

**Comment by dries007** [comment]
Try setting the force_protocol_version property on your ClientFactory.
See https://quarry.readthedocs.io/en/latest/networking/factories_protocols.html#quarry.net.client.ClientFactory.force_protocol_version
