### ISSUE TITLE
getting error trying to make proxy with python

### ISSUE THREAD

**Issue by fanda857** [barneygale/quarry#139]
#im trying to make proxy with python and when i join i get this error
Auth failed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]

**Comment by gamecocks08** [comment]
That's an issue with twisted. there is an issue that was solved that worked for me. Go back through and check one of those.

**Comment by TrentLangford** [comment]
Did you end up finding what caused the issue in twisted? The website's logs are broken for solved tickets within the last 30 days.

**Comment by Jerrylum** [comment]
I hope #135 can solve your problem.

**Comment by 3arthquake3** [comment]
It doesn't show the error anymore.. since i ran it on my linux server and specified the ssl cert file but when i join the proxy server, it just shows: encrypting then joinning and it just freezes there for a few seconds and eventually connection time out
