### ISSUE TITLE
Channels for quary ?

### ISSUE THREAD

**Issue by aaps** [barneygale/quarry#14]
More a request, minecraft has support for channels over wich plugins can send messages.
Since minecraft server use a lot of plugins thise days there should perhaps be the posibility to use this channels ?

**Comment by barneygale** [comment]
Hi. This should already be possible. 

To receive a message, hook the 'plugin_message' packet:

```py
    def packet_plugin_message(self, buff):
        p_channel_name = buff.unpack_string()
        p_channel_data = buff.read()
        # do something with the message
```

To send a message:

```py
self.send_packet("plugin_message", self.buff_type.pack_string("yourchannelname") + b"yourchanneldata")
```

Does that work for you?

**Comment by aaps** [comment]
Hey Barney

Oh yeah that works, but it will only send a package to register, so that it has a channel number to send to.
Like the number packet_upstream_player_position usses to get noticed.
So i will get the register data bug nog the data that gos over that channel.

I might be wrong but i think that is the gist of it

Greetings !

**Comment by barneygale** [comment]
I don't know much about plugin channels, but perhaps you have to acknowledge the registration? Quarry doesn't do any handling of plugin channels - you'll need to build that yourself.

**Comment by aaps** [comment]
Well, im kanda bussy with my own thing like seperating the nether chunks end chunks and overworld chunks, but when i need it i will get to it !

**Comment by barneygale** [comment]
Nice one. Log an issue if you come across any bugs.
