### ISSUE TITLE
Auth failed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]

### ISSUE THREAD

**Issue by TrentLangford** [barneygale/quarry#143]
I was attempting to set up a proxy (using the example chat proxy as a test) for a local vanilla server and received this error message. Anyone know why this occurs? Is this my mistake?

**Comment by TrentLangford** [comment]
This is a duplicate issue that seems to come from the twisted library itself. Still don't know what's going on.

**Comment by jakecrowley** [comment]
> This is a duplicate issue that seems to come from the twisted library itself. Still don't know what's going on.

I'm having this same error, were you able to resolve it?

**Comment by hendrikbgr** [comment]
any news on this?

**Comment by jakecrowley** [comment]
> any news on this?

Running it on Linux instead of Windows worked for me. You can use Git Bash or WSL if you want to still use Windows.
