### ISSUE TITLE
Trying to use the proxy for online mode

### ISSUE THREAD

**Issue by Sunderw3k** [barneygale/quarry#149]
ive seen a bit of source code and I think i need to use quarry.net.auth Profile() class - it requires the client token, access token, username and UUID. Im confused about the client and access - i think that the client token is used to make an access token and the access token is used for auth to servers. Eitherway, how can I get them all - and is there a simpler way

**Comment by Jerrylum** [comment]
I hope #135 can help you.

https://github.com/barneygale/quarry/issues/135#issuecomment-1088143509

Also read: https://wiki.vg/Authentication

**Comment by Sunderw3k** [comment]
so does the comment fix everything for me? Ill try it - thanks

**Comment by Sunderw3k** [comment]
oops crap forgot to close the issue. mb
