### ISSUE TITLE
How to turn Entity_ID into Player Name?

### ISSUE THREAD

**Issue by Lilyp3892** [barneygale/quarry#150]
How I can convert the Entity_ID of a player into their UUID or name?

**Comment by Jerrylum** [comment]
You can store the UUID and EntityID in a dictionary. But I would like to know what're you trying do actually?

**Comment by Lilyp3892** [comment]
> You can store the UUID and EntityID in a dictionary. But I would like to know what're you trying do actually?

I'm using packet_downstream_entity_equipment to get entity's equipment and i want to be able to get a players equipment from their username

**Comment by Jerrylum** [comment]
Here you're: https://gist.github.com/Jerrylum/fc8ac643d63dd0e7716046f59bb8f8c3

**Comment by Lilyp3892** [comment]
> Here you're: https://gist.github.com/Jerrylum/fc8ac643d63dd0e7716046f59bb8f8c3

Thank you!
