### ISSUE TITLE
 Auth failed when trying to joing proxy server

### ISSUE THREAD

**Issue by 1BlobFishGuy** [barneygale/quarry#152]
This is the full error :
Auth failed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]

This error comes every time I try to connect to a proxy server. My version is 1.18.2 and i'm using a private paper server hosted on my machine. Please help, thanks in advance.

**Comment by cody-ferguson** [comment]
Same

**Comment by Rwkeith** [comment]
Simply add `factory.online_mode = False` to your proxy

**Comment by 1BlobFishGuy** [comment]
Thanks a lot.
