### ISSUE TITLE
Possible support for mods

### ISSUE THREAD

**Issue by rakesh37187** [barneygale/quarry#153]
I wish to experiment with packets from minecraft mods. I tried setting up Quarry for a modpack but sadly I was not able to join the server since it threw an error stating it requires forge/fml. I am not sure how to proceed with that hence this issue.

**Comment by rakesh37187** [comment]
After looking a bit more into the code and understanding it a bit I can see that on handshake the server checks for "\x00FML\x00" after the host. Maybe someone could look more into it?

**Comment by MajliTech** [comment]
This (propably) is going to be `wontfix`

**Comment by dries007** [comment]
Forge/FML has a whole handshake system to make sure you can't join servers without the required mods installed. IMO Implementing any of it is not really in scope of this project.

I recommend you insert a bunch of logging code in a real client via a Forge/FML mod to log how the interactions work and work from there. It's not going to be easy I think, and probably also quite version dependant.

I'm closing this issue as "not in scope", but if you do find/create a solution, feel free to comment here.
