### ISSUE TITLE
Proxy Protocol

### ISSUE THREAD

**Issue by Chiharu-Hagihara** [barneygale/quarry#155]
Hi!
I'm creating downtime server with quarry library. we use proxy protocol on our network, actually. but i could't find how to use proxy protocol with quarry. anyone tell me that? if you already post that on documentation, i will apologize about that.

**Comment by koliwbr** [comment]
Hi, you can find examples in /example directory. (Here is proxy example)[https://github.com/barneygale/quarry/blob/master/examples/proxy_hide_chat.py]

**Comment by Chiharu-Hagihara** [comment]
how many rows can i find it?

**Comment by koliwbr** [comment]
> how many rows can i find it?

I don't understand, please write more clearly what effect you want to get and where is your problem

**Comment by Chiharu-Hagihara** [comment]
Do you know proxy protocol? Usually minecraft proxies have proxy protocol option in config.yml.
Our network is using proxy protocol. So, we need to use it on creating downtime server. but I couldn't find how to enable proxy protocol with quarry.

**Comment by koliwbr** [comment]
Quarry is Minecraft library for Python. One of options is to use it as proxy. If you using BungeeCord or something similar, run quary server only for localhost and set port and BungeeCord port to same value.

**Comment by Chiharu-Hagihara** [comment]
Do you know proxy protocol?
I know about your all reply.
I already created quarry-program as proxy.
i wanna know HOW TO ENABLE PROXY PROTOCOL OPTION.

**Comment by koliwbr** [comment]
You mean SOCKS proxy or something similar?

**Comment by Chiharu-Hagihara** [comment]
probably yep
