### ISSUE TITLE
Cannot send message

### ISSUE THREAD

**Issue by aviddiscorduser** [barneygale/quarry#162]
How do I send a message to the server chat on an Offline (Cracked) Account.

I tried using several methods, but none of them have worked properly. They all use "self" but I cannot find what the "self" is.

someone please help

**Comment by davidawesome02** [comment]
Do you have discord, I can chat there and help you, or can you post your code.

**Comment by aviddiscorduser** [comment]
> Do you have discord, I can chat there and help you, or can you post your code.
> (edit)
> Of corse you do, looking at Your user and name
> please send your name and tag

my discord is drip#6930 @davidawesome02

**Comment by davidawesome02** [comment]
> 

ok, I added you, I suggest you edit out your name now and If you wana just talk in text I can do that, Message me when your avaliable.

**Comment by aviddiscorduser** [comment]
Thank you. Issue resolved
