### ISSUE TITLE
Question: What is better quarry or pycraft?

### ISSUE THREAD

**Issue by olegpokhilchenko** [barneygale/quarry#165]
What is better for me quarry or [pycraft](https://github.com/ammaraskar/pyCraft) ?

**Context:**
I want to make many clients at once.  Aspects are important to me: Performance and stability (For example, catching errors).

**Comment by dries007** [comment]
I have no idea how pycraft works, so I can only give you information about Quarry.

Quarry uses Twisted, it's event based, and basically behaves like async code. While I haven't done so I think you can (relatively easily) use multiple clients in the same thread. 
If you end up using Quarry, we'd be happy to accept a PR with an example, so others can learn.
