### ISSUE TITLE
Can this work with py-script

### ISSUE THREAD

**Issue by davidawesome02** [barneygale/quarry#166]
I know this is dumb, because I belive that js blocks doing direct network things like quarry dose, but can I run it in py-script?
[https://pyscript.net/](url)
my error in testing:
```PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 286, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'quarry'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.```

my code:
```<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
        <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
        <py-env>
            - twisted
            - quarry
        </py-env>
    </head>
    <body>
        <py-script src="./proxy8.py"></py-script>
    </body>
    
</html>
```

I am not uploading the proxy

**Comment by ANDREI12333** [comment]
py-script doesn't support most of the modules used by quarry. Which means **NO** go away

**Comment by davidawesome02** [comment]
@ANDREI12333 Ok, you went onto a year old question from when I started this, Im sorry past me was a dumbass, but dont fucking nectopost to be a jerk.

Also its not the modules that are not supported but instead the networking protocols exposed via tcp comunication. Because javascript has limited access to your computer it is unable to open ports or do raw comunication (yes webrtc witch requires multiple servers has similar propertys, but is not tcp).

Thankyou, please learn how to answer questions, or ask someone to close and goodnight - david


> py-script doesn't support most of the modules used by quarry. Which means **NO** go away

**Comment by davidawesome02** [comment]
> You are a complete idiot. I thought i was done with your stupid issue.
@ANDREI12333 

You are a complete and total moron who cant even read that 
1. the issue is fucking closed
2. the date, THIS IS A YEAR AND A HALF OLD


(and mby you wouldn't have posted that I am a idiot if you could read the part where I said I was when writing that)

and a final response to (I thought i was done with your stupid issue.)
Yes we all were, until you desided to comment on it.

**Comment by davidawesome02** [comment]
> You are a complete idiot. I thought i was done with your stupid issue.

and yes I am just sending this to annoy you 3 weeks later

**Comment by ANDREI12333** [comment]
@davidawesome02 lol

**Comment by ANDREI12333** [comment]
> > You are a complete idiot. I thought i was done with your stupid issue.
> > @ANDREI12333
> 
> You are a complete and total moron who cant even read that
> 
> 1. the issue is fucking closed
> 2. the date, THIS IS A YEAR AND A HALF OLD
> 
> (and mby you wouldn't have posted that I am a idiot if you could read the part where I said I was when writing that)
> 
> and a final response to (I thought i was done with your stupid issue.) Yes we all were, until you desided to comment on it.
SO IM THE ONE WHO NECROPOSTED? LAST MESSAGE YOU SENT?? YOU DIDNT CLOSE THE ISSUE IDIOT.
