### ISSUE TITLE
Why chunk support is deprecated?

### ISSUE THREAD

**Issue by olegpokhilchenko** [barneygale/quarry#175]
Why chunk unpacking doesn't work on modern versions?
Why was the last commit 3 months ago?
Is this project outdated?
Will it continue to grow?

**Comment by dries007** [comment]
> Why was the last commit 3 months ago?

If you want I can send you my hourly rates, then I can make sure to make a commit every day. /s

This project is maintained by volunteers when they have time available. Posts like these are don't help with motivation either.

> Is this project outdated?

Depends on your point of view. It works perfectly well for the versions marked as supported. Other (newer) versions may work if you do some work yourself (at which point you're free to PR it into the main code).

> Will it continue to grow?

I use this project for a server implementation, so I will maintain that as long as I maintain that project. 
That means I will continue to add new versions of MC when I have the time for it.

> Why chunk unpacking doesn't work on modern versions?

I don't know. I guess for format changed and nobody has bothered to implement and PR the needed changes to support the new format. Personally I don't need it, so I don't care if it's missing.
