### ISSUE TITLE
Minecraft 1.10 support

### ISSUE THREAD

**Issue by minecrafter** [barneygale/quarry#19]
It would be nice if quarry had Minecraft 1.10 support. I have tried a few Minecraft protocol libraries, and so far only Quarry seems to fit my needs (multi-version support is vital to my use case).

**Comment by Gjum** [comment]
if it's just a case of updating [packets.csv](https://github.com/barneygale/quarry/blob/master/quarry/data/packets.csv), [minecraft-data](https://github.com/PrismarineJS/minecraft-data/) would probably help a lot.

**Comment by williammck** [comment]
Fixed in 36e6e0d.

**Comment by minecrafter** [comment]
Awesome! 👍

**Comment by barneygale** [comment]
I've made a new pypi release that includes williammck's fix
