### ISSUE TITLE
The chat logger example doesn't work, microsoft login.

### ISSUE THREAD

**Issue by TheTrevi** [barneygale/quarry#190]
When I try running the code from the [chat logger example](https://quarry.readthedocs.io/en/latest/examples.html#chat-logger) it doesn't work, if I put a print statement after factory.connect(args.host, args.port) it gets executed which means it connects properly to the server, but it just stops there and it does nothing else.

The only changes I made to the code are in the auth.py file from the library; in the ProfileCLI class, in the make_profile func; where I changed from Profile.from_credential to Profile.from_token (since I found a library called msmcauth that can retrieve your Minecraft session ID, username, and uuid from your Microsoft account).

I don't know if the problem is that I'm trying to connect to hypixel which is the biggest server or what, I even tried with other public servers but the issues don't seem to resolve. 
Can someone help me, I would be very grateful

**Comment by KyngK** [comment]
I've been having this same issue, and unfortunately I can't help much. However I will note that I don't think the client is actually connecting to the server, because if you try logging on with the game, and then log on with the chat logger, you don't get kicked out.

**Comment by davidawesome02** [comment]
It is mostlikely a bug with how microsoft is doing now, the owner of the project stoped realy working on it a few months back,

which version did you log in on, because the new chat encryption is not built into it, also now in the latest update (came out a few days ago) the packets are able to come in a unsupported format

**Comment by KyngK** [comment]
I think I was using 1.19
