### ISSUE TITLE
Support for 1.19 is purely fictional.

### ISSUE THREAD

**Issue by MajliTech** [barneygale/quarry#196]
I couldn't get sending chat as a client from unsupported 1.19.4, 1.19.3 or 1.19.2. The fact that this is marked as a supported is kinda wrong, because when sending chat the kick message is:
`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(8) exceeds writerIndex(24): PooledUnsafeDirectByteBuf(ridx: 24, widx: 24, cap: 24)`
This project is abandoned, and someone with enough Minecraft and Python skills, time and patience should take it over.

**Comment by MajliTech** [comment]
#191

**Comment by MajliTech** [comment]
#191 should also be noted

**Comment by dries007** [comment]
Where do you see it mentioned that 1.19.3 or 1.19.4 is supported? It's not in the readme or release notes, so the fictional support is entirely a figment of your imagination.

I know for a fact 1.19, 1.19.1 and 1.19.2 work (at least for rudimentary chat stuff), as I use it for MCLink. It's possible there are bugs with the chat example code, but I don't think so as I generally test that before making a release.

**Comment by MajliTech** [comment]
Ok, but even for 1.19.2, it ain't working

**Comment by MajliTech** [comment]
Ok, now I know where I got 1.19.3 someone made a try to add support.

**Comment by dries007** [comment]
Considering I'm actively using it without issues at the moment, I tend to disagree. As released, 1.19.2 works. It might require some tweaks to get all the features you need to work, but the basics are there.

As for the 1.19.3/1.19.4 support: There is a merge request, but that's not in a mergeable state. If you want to be of help, try to get that working and make your own merge request or issue with description of what needs to change to implement support.
The best resources are the existing code and [wiki.vg](http://wiki.vg). Good luck; have fun. I guess you'll find out soon enough why it sometimes takes so long to get a new version supported. I've worked a bit on and off on the support for the missing 1.19.x versions, but have not gotten very far.

As a sidenote: Please stop spamming issues with comments, unless you actually have a solution to a problem. All this activity just creates email/notification spam, which then leads to the project being more ignored by the maintainers.
