### ISSUE TITLE
How to send chat message

### ISSUE THREAD

**Issue by Bottersnike** [barneygale/quarry#21]
How would I go about sending a message to chat?

**Comment by TiberiumPY** [comment]
You need to implement http://wiki.vg/Protocol#Chat_Message_.28serverbound.29

**Comment by TiberiumPY** [comment]
It's very simple

**Comment by Bottersnike** [comment]
I get that, but from building upon the chat reading example, how would I implement chat sending unsing the quarry API?

**Comment by TiberiumPY** [comment]
https://github.com/barneygale/quarry/blob/master/examples/client_chat_logger.py

You need to use self.send_packet with constructed buff

**Comment by TiberiumPY** [comment]
self.send_packet("chat_message", self.buff_type.pack_string("hello world"))
You can try something like this

**Comment by Bottersnike** [comment]
Thanks :)
