### ISSUE TITLE
latest pip release has debug print statements

### ISSUE THREAD

**Issue by Gjum** [barneygale/quarry#24]
I just updated to 0.6.2 through pip and got a bundle with some print-debug statements left in auth.py: [diff master vs pip](https://gist.github.com/Gjum/4270de2e9b336dd968ce3485cdbd941f/revisions)

And now it crashed on my python 3 project because of the old `print` syntax.

Sounds like you need another one of these ;-) https://github.com/barneygale/quarry/commit/e8e44c5fb6f6421054ab1edff9764dc479586b3f#diff-db23dcd814354c954091a9b90dbfd92aR12

Thanks and keep up the good work!

**Comment by barneygale** [comment]
Bollocks, sorry.

**Comment by barneygale** [comment]
Give 0.6.3 a go?

**Comment by Gjum** [comment]
Perfect, thanks.
