### ISSUE TITLE
1.7-1.11.2

### ISSUE THREAD

**Issue by maxim19116** [barneygale/quarry#27]
How to add support for 1.7-1.11.2 server?

**Comment by barneygale** [comment]
What do you mean?

**Comment by TiberiumPY** [comment]
@barneygale he doesn't know English well, he wants a server with Minecraft version from 1.7 to 1.11.2 support (as ProtocolSupport in Spigot).

**Comment by maxim19116** [comment]
Thanks!

**Comment by maxim19116** [comment]
![image](https://cloud.githubusercontent.com/assets/21990737/24042903/2a3438f0-0b25-11e7-84c7-4af510bbf561.png)

**Comment by TiberiumPY** [comment]
@maxim19116 you need to implement packets in play mode yourself, including support for different versions

**Comment by barneygale** [comment]
If you want to report a bug, please provide a reproduction case.

**Comment by maxim19116** [comment]
@TiberiumPY How to do this?

**Comment by TiberiumPY** [comment]
@maxim19116 http://quarry.readthedocs.io/en/latest/

**Comment by TiberiumPY** [comment]
@maxim19116 http://quarry.readthedocs.io/en/latest/

**Comment by maxim19116** [comment]
@TiberiumPY and where?

**Comment by TiberiumPY** [comment]
@maxim19116 please, stop asking questions like that.
There's enough examples and another project to get started

**Comment by maxim19116** [comment]
Ok

**Comment by barneygale** [comment]
Please provide detail of what you're attempting to do, or problems you're having, before reporting future issues. Even taking into account the language barrier there's not enough detail for me to go on - no code, no stack traces, etc.
