### ISSUE TITLE
World loading

### ISSUE THREAD

**Issue by vueu** [barneygale/quarry#28]
Hello, this is in no way an issue, but I felt like it might've been the only reasonable way to get in contact with you.

How would I go about sending a packet of the world to the client? I realize generating would be tough, so I've pre-generated one. Can I load this file and send it via packets somehow? Super new at this, and if this is a dumb/hard question to answer feel free to excuse my ignorance!

**Comment by barneygale** [comment]
Hi! The format of a minecraft world [on disk](http://wiki.vg/Map_Format) is different to how its laid out [on the wire](http://wiki.vg/SMP_Map_Format) (also see the [draft version](http://wiki.vg/User:Pokechu22/Chunk_Format) of that page). You need to send a bunch of [``chunk_data``](http://wiki.vg/Protocol#Chunk_Data) packets to the client, but the format of these packets is quite complicated, and I don't have any examples on hand. I'll have a look at adding chunk pack/unpack to quarry, but it might take a while. Let me know if you get there first.

**Comment by vueu** [comment]
Will do, thanks a lot for the help. I understand it a lot better. 👍

**Comment by barneygale** [comment]
This might be useful for the network side: https://github.com/barneygale/quarry/commit/731ecfff3c34bd0e948f98bf8e945c5a9f4fdb96

**Comment by vueu** [comment]
Awesome! Thanks for investing your time into this. I'll be sure to experiment with it tomorrow night :smile:

**Comment by barneygale** [comment]
Did you get a chance to test this yet?

**Comment by vueu** [comment]
I didn't! Sorry, I've just been busy with a ton of other weird stuff.

**Comment by chibill** [comment]
Just as a side note shouldn't pack_chunk and unpack_chunk be like pack_chunk_section and unpack_chunk_section. As that is what they are packing and unpacking. 

That way not to confuse people thinking it packs and unpacks the full chunk.

**Comment by barneygale** [comment]
It's a reasonable point. I think "chunk" is used for 16x16x16 in some circumstances but sticking "section" in there will clear up any ambiguity

**Comment by barneygale** [comment]
The `chunk` --> `chunk_section` rename happened in 7be6f177f24eb4b5a9f6cb6df18fa890858708d0.

I'm closing this as chunk packing/unpack is *in principle* supported. @vueu, if you have any problems with world loading please do raise another issue!

Thanks
