### ISSUE TITLE
1.7 - 1.11 support. Please give examples 

### ISSUE THREAD

**Issue by thelex337** [barneygale/quarry#29]
give examples for support multiple version

**Comment by barneygale** [comment]
Quarry's own packet handers support 1.7-1.11; in your own handlers you'll like to switch on `self.protocol_version` [as seen here](https://github.com/barneygale/quarry/blob/master/examples/client_messenger.py#L34-L39)

**Comment by thelex337** [comment]
I meant to add support for 1.11 on the server

**Comment by TiberiumN** [comment]
@barneygale he's the friend of @maxim19116, he'll just waste your time

**Comment by TiberiumN** [comment]
@thelex337 and for your question:
as @barneygale said, just make some conditions based on self.protocol_version

**Comment by TiberiumN** [comment]
@thelex337 if you can't understand this, it's your problem, so you don't need to put issues there

**Comment by barneygale** [comment]
I'll leave this open for one more day in case @thelex337 wants to ask an answerable question, but my patience is otherwise wearing a little thin.

**Comment by thelex337** [comment]
@TiberiumN and @barneygale i asked for an example of a server that supports 1.11 and 1.8

**Comment by TiberiumN** [comment]
@thelex337 
https://github.com/barneygale/quarry/blob/master/examples/server_auth.py
:)

**Comment by barneygale** [comment]
If you're still struggling with this issue, please share your code. You're asking about supporting *multiple* versions, so I can only assume you've got it working in one version already. From that point forward it's conceptually simple to support another protocol version: switch on `self.protocol_version` and implement the other packet format. If you clone this repository and `git grep protocol_version` you can find further examples of this.
