### ISSUE TITLE
stone in first slot

### ISSUE THREAD

**Issue by Dranorandin17** [barneygale/quarry#30]
Hello, how to send a packet, that in 1 slot a stone appeared, how can this be organized?

**Comment by barneygale** [comment]
I think you need to send a [`window_items`](http://wiki.vg/Protocol#Window_Items) packet.

**Comment by Gjum** [comment]
http://wiki.vg/How_to_Write_a_Client#Inventory_and_Crafting

that section should still apply

**Comment by Dranorandin17** [comment]
@barneygale Can you give me how to use it in python?

**Comment by Dranorandin17** [comment]
I need the simplest solution

**Comment by barneygale** [comment]
I can't provide packet-by-packet support. Look at the examples for how to send packets, read the [minecraft developer documentation](http://wiki.vg), and read the [quarry documentation](http://quarry.readthedocs.io/). If you're developing a server you'll almost certainly want some kind of proxy so you can see what the Mojang client/server send.
