### ISSUE TITLE
Fmt, and where to get it?

### ISSUE THREAD

**Issue by Dranorandin17** [barneygale/quarry#32]
Hello, where are these values located on wiki.vg? I realized that this is fmt, but where to get it for version 1.9?
http://imgdepo.com/id/10637122.jpg

**Comment by TiberiumN** [comment]
@Dranorandin17
http://wiki.vg/Protocol#Player_Position_And_Look_.28clientbound.29
You see there's types: double double double float float byte?
You can check documentation for "struct" module here - https://docs.python.org/3.5/library/struct.html#format-characters

So result format would be "dddffb", as in quarry

**Comment by Dranorandin17** [comment]
thank you, sir

**Comment by Dranorandin17** [comment]
Can you help me again? How to get x, y, z player? Or is it impossible?

**Comment by Dranorandin17** [comment]
Can you help me again? How to get x, y, z player? Or is it impossible?

**Comment by TiberiumN** [comment]
@Dranorandin17 you should store it by yourself.
So if you're changing player position, or he's changing his position himself, you will need to make a list (or dict) to store players and their properties
You can look there - https://github.com/TiberiumN/puremine  (but sorry for not-so-good code)
