### ISSUE TITLE
update_health need help

### ISSUE THREAD

**Issue by Dranorandin17** [barneygale/quarry#34]
self.send_packet("update_health", self.buff_type.pack('fid', float(19), 15, float(0.0)) + self.buff_type.pack_varint(1))

Does not work, what did I do wrong?

**Comment by barneygale** [comment]
http://wiki.vg/Protocol#Update_Health

The packet has 3 fields but you're packing 4. The payload should be `self.buff_type.pack('f', 0) + self.buff_type.pack_varint(1) + self.buff_type.pack('f', 2)` to pack health=0, food=1, saturation=2
