### ISSUE TITLE
"unpack" not working

### ISSUE THREAD

**Issue by maxim19116** [barneygale/quarry#37]
![1](https://user-images.githubusercontent.com/21990737/28697148-a39fb8ce-7342-11e7-8702-f11425ed8794.PNG)
![2](https://user-images.githubusercontent.com/21990737/28697147-a39fcf6c-7342-11e7-8d3b-08ef27244fbf.PNG)

In the terminal nothing.

**Comment by TiberiumN** [comment]
Because this packet is server-only.
It means that only server sends this packet to client, not client.
You need only code from second screenshot

**Comment by TiberiumN** [comment]
http://wiki.vg/Protocol#Update_Health

**Comment by TiberiumN** [comment]
Ah, your second code is invalid: you need to use http://wiki.vg/Protocol#Set_Experience to set experience

**Comment by maxim19116** [comment]
@TiberiumN А можно ли распаковать данный пакет&

**Comment by TiberiumN** [comment]
@maxim19116 зачем? Его посылает сервер клиенту

**Comment by maxim19116** [comment]
@TiberiumN Хорошо, спасибо.
