### ISSUE TITLE
Pack slot data?

### ISSUE THREAD

**Issue by DimaVelocity** [barneygale/quarry#39]
Hi, barney, how to send "Set_slot", in your library there is no such as "pack_SlotData", but there is "unpack_slot". How can I send it?

http://wiki.vg/Protocol#Set_Slot

**Comment by Yardanico** [comment]
@DimaVelocity there's set_slot packet

**Comment by DimaVelocity** [comment]
@Yardanico I do not understand you.

**Comment by barneygale** [comment]
Hi,

You're right that there's no `Buffer.pack_slot()` at the moment. I'll look into adding it! Until then you might want to write your own method based on [the docs](http://wiki.vg/Slot_Data) and `Buffer.pack()` / `Buffer.pack_nbt()`.

**Comment by barneygale** [comment]
I've added a `Buffer.pack_slot()` method in 78d8c2aee461e875e1f2669c233f4cfad6000f8a, so you should be able to send a `set_slot` packet like so:

```python
self.send_packet("set_slot", 
    self.buff_type.pack('bh', window, slot_num) + \
    self.buff_type.pack_slot(id, count, damage, tag))
```

**Comment by DimaVelocity** [comment]
Thanks!
