### ISSUE TITLE
Non py3 syntax used

### ISSUE THREAD

**Issue by dries007** [barneygale/quarry#41]
`except Exception, e:` is no longer valid syntax in python 3, it's now `except Exception as e:`

I believe this syntax is also legal on 2.7, but I don't know off the top of my head.
The only place it's used is https://github.com/barneygale/quarry/blob/master/quarry/net/ticker.py#L123

Thanks for this btw, hopefully I can replace my mess of nodeJS, php and handwritten SQL with a nice neat python package with this.

**EDIT:**
There are a few other things not py3 friendly, I'll keep a list as I find things:
- [x] The exception syntax
- [x] The favicon is being loaded as a text file

**Comment by barneygale** [comment]
Thanks for reporting this - I've pushed 4831cc1812d392ad5a4cc79fea5d43bd4aba805e which should address the ticker.py exception and server.py favicon loading issues. Perhaps we should leave this issue open until you're happy there's no python 3 gremlins left to be discovered?

**Comment by dries007** [comment]
That sounds like a good idea. Hopefully there's few :smile:

**Comment by wgaylord** [comment]
I can conform `except Exception as e:` is legal in python 2.7 (I used it even in 2.6 and maybe earlier.)

**Comment by barneygale** [comment]
The `as` syntax is valid in 2.6+

**Comment by barneygale** [comment]
Hi @dries007, I'll close this issue if you didn't encounter any further problems?

**Comment by dries007** [comment]
I have not come across any new issues.
