### ISSUE TITLE
Getting an image from the map

### ISSUE THREAD

**Issue by Dranorandin17** [barneygale/quarry#42]
I would like to ask how in the packet Map http://wiki.vg/Protocol#Map get the image in jpg format? Thank you in advance.

**Comment by Yardanico** [comment]
You can't get JPG map from protocol, you should construct JPG (or PNG) yourself, probably using pillow

**Comment by barneygale** [comment]
You can decode the `map` packet like this:

```python
def packet_map(self, buff):
    damage = buff.unpack_varint()
    scale, tracking_position = buff.unpack('B?')
    
    icon_count = buff.unpack_varint()
    icons = []
    for _ in range(icon_count):
        icons.append(buff.unpack('BBB'))

    columns = buff.unpack('B')
    if columns > 0:
        rows, x, z = buff.unpack('BBB')
        length = buff.unpack_varint()
        data = buff.unpack('B'*length)
```

From there you have `data`, which is an array with 1 byte per pixel on the map. The values might be color IDs (as suggested [here](https://minecraft.gamepedia.com/Map_item_format)) but I couldn't make sense of it. When you have the color lookup code working, you could use pillow to generate the image (as @Yardanico suggests)
