### ISSUE TITLE
Proxy connection

### ISSUE THREAD

**Issue by Dranorandin17** [barneygale/quarry#43]
How through the proxy to redirect the player from the server to the server, I did through this code:
```

self.connect_host = '127.0.0.1'
self.connect_port = 25568
self.connect ()

```
But when this code is executed, the player flips from the server to the server, but there is a long download of the world:

![loadworld](https://user-images.githubusercontent.com/27915831/32575822-1e4da24e-c4e6-11e7-996f-b8275e207a8b.PNG)

How and with what to do?

**Comment by barneygale** [comment]
1. Are the client, proxy and server running on the same host, or is part of this happening over the internet?
2. Does the client eventually get in-game, or are you stuck permanently on 'Downloading terrain'?

**Comment by Dranorandin17** [comment]
@barneygale 

1. Internet
2. constantly 'Downloading terrain'

**Comment by Dranorandin17** [comment]
Hey, barney

**Comment by barneygale** [comment]
No idea why this would happen. Without a repro case I can't help, sorry.
