### ISSUE TITLE
BlockArray.__setitem__ doesn't work when BlockArray is loaded by buffer.unpack_chunk_section

### ISSUE THREAD

**Issue by apuly** [barneygale/quarry#45]
The buffer.unpack_chunk_section loads the LightArrays and BlockArray as a tuple (due to the use of the struct.unpack function).
Due to the immutable nature of tuples, it is not possible to use the modify the data in the BlockArray, even though the __setitem__function implies that this should be possible. 

I've fixed the issue locally by converting the tuple into a list before initialising the BlockArray and LightArrays.

**Comment by barneygale** [comment]
This should be fixed in quarry 1.0
