### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by smilechaser** [barneygale/quarry#47]
This looks like a really cool project with a lot of effort invested in it. I know I would like to use it, but am always hesitant when there is no explicit license provided.

If you have no concerns about a particular license, may I suggest the MIT license? I feel this would give users/contributors the most flexibility.

Thanks!

**Comment by Yardanico** [comment]
https://pypi.org/project/quarry/ it says "MIT"

**Comment by Yardanico** [comment]
@smilechaser there is a license - https://github.com/barneygale/quarry/blob/master/COPYING.txt

**Comment by smilechaser** [comment]
Ahh good to know - thanks!

It still might be a good idea to add a `LICENSE.md` file though:

https://help.github.com/articles/adding-a-license-to-a-repository/

Just a friendly suggestion - feel free to close this if you don't agree.

**Comment by Yardanico** [comment]
@smilechaser I'm not the maintaner nor the contributor to this repo, and about license file - it's enough to add `LICENSE`, not `LICENSE.md` :)

**Comment by barneygale** [comment]
GitHub [say](https://help.github.com/articles/licensing-a-repository/#detecting-a-license) that they use a library called [Licensee](https://github.com/benbalter/licensee) for detecting licenses, and this [looks like](https://github.com/benbalter/licensee/blob/2ac4b6d4fccf11cd947accf17e80d04c7735c2b6/lib/licensee/project_files/license_file.rb#L30) it should detect `COPYING.txt`. I'll look into it.

**Comment by Yardanico** [comment]
@barneygale `COPYING.md` is not the same as `COPYING.txt`

**Comment by barneygale** [comment]
Never trust the comments.

**Comment by barneygale** [comment]
```
      PREFERRED_EXT = %w[md markdown txt].freeze
      PREFERRED_EXT_REGEX = /\.#{Regexp.union(PREFERRED_EXT)}\z/
```
