### ISSUE TITLE
unsupported protocol version: 0 While joining server via domain

### ISSUE THREAD

**Issue by peacers** [barneygale/quarry#51]
Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "C:\Users\rj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quarry\net\client.py", line 60, in connection_made
    self.protocol_version = yield factory.detected_protocol_version
quarry.net.protocol.ProtocolError: Unsupported protocol version: 0

Only happens when I try and join the server using a domain.

**Comment by barneygale** [comment]
Sorry for the long delay. Can you share the IP of the server?
