### ISSUE TITLE
Online mode with proxy

### ISSUE THREAD

**Issue by CarbonNeuron** [barneygale/quarry#54]
Hello! I was wondering how it would be possible to allow the proxy to connect to an online server, if you explicitly have account information, like username and password, tokens and whatnot.

**Comment by barneygale** [comment]
Sorry for the delay. Yes, this is possible! You want to store the online-mode profile you want use on your downstream factory, e.g.:

```python
@defer.inlineCallbacks
def run():
    factory = MyDownstreamFactory()
    factory.upstream_profile = yield Profile.from_file(display_name="mynickname")
    factory.listen("127.0.0.1", 25565)
```

Then all you need to do is implement `MyBridge.make_profile()` to return that object:

```python
    def make_profile(self):
        return self.downstream_factory.upstream_profile
```

**Comment by CarbonNeuron** [comment]
I'm having trouble implementing this into the example provided, proxy_hide_chat

it just exits the program without any error message. Any help would be appreciated.

**Comment by barneygale** [comment]
You're calling `reactor.run()`?

**Comment by thelennylord** [comment]
I'm experiencing the same issue here. After reaching `factory.upstream_profile = yield Profile.from_file(display_name="mynickname")`, the program exits without any errors. Removing the line makes the program work as intended but in offline mode. This doesn't seem to be exclusive to the proxy_hide_chat example, as it's occurring with the skeleton proxy too.

**Comment by thelennylord** [comment]
Whoops! I was calling `reactor.run()` inside the run function. After calling it in the main function, everything started to work normally. 

OP must have done the same mistake as me.

**Comment by CarbonNeuron** [comment]
Probably, I'll try this to see if it works
