### ISSUE TITLE
How to send over mixed-data array

### ISSUE THREAD

**Issue by martmists** [barneygale/quarry#57]
How do I send over a mixed-data array like the `player_list_item` packet, which requires an Array with strings, varints, etc to be sent over?

**Comment by williammck** [comment]
The "array" is really the commonly formatted data appended over and over again.

Here's an example from one of my older projects of modifying the UUIDs in the `player_list_item` packet - it may prove helpful for you: https://gist.github.com/williammck/5bbc95e32c4100f53cf8ff1d7223ffbb

**Comment by barneygale** [comment]
Thanks for answering @williammck!
