### ISSUE TITLE
1.14 support

### ISSUE THREAD

**Issue by dries007** [barneygale/quarry#59]
Hi, I know opening an issue to ask for an ETA is bad etiquette, but I'm doing it anyway :)

You have any idea when you'll push a version with 1.14 support (even basic, login & chat only) to pypi?

If it's usable in that state already, please let me know, then I can update my application. Thanks!

**Comment by barneygale** [comment]
Will get a new version pushed this evening!

**Comment by jamesguessis** [comment]
what about 1.14.1/1.14.2?

**Comment by barneygale** [comment]
Sorry for the long delay. I've pushed quarry 1.3 which supports 1.14, 1.14.1 and 1.14.2. Shout if you hit any problems.

**Comment by untuned** [comment]
@barneygale Does this include 1.14.3 (and soon 1.14.4)?

**Comment by barneygale** [comment]
@untuned I've pushed a162d98d3ef396ba19ae8a7548de038575ad774e for 1.14.3 support.
