### ISSUE TITLE
Is there a block under player's feet

### ISSUE THREAD

**Issue by MineFlayerPC** [barneygale/quarry#62]
How can I make a check whether there is a land under my bot, if it is not there, then fall into the block below, tell me how to do this in your library, as I recently began to study this topic, thanks

**Comment by rom1504** [comment]
You can simply read the code of the library in your pseudo to check how
it's done.

**Comment by MineFlayerPC** [comment]
Please tell me, I still can’t figure it out

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/physics.js

+ Of course you need to implement chunk parsing

**Comment by MineFlayerPC** [comment]
This I can not do) I know about your library

**Comment by rom1504** [comment]
You need to reimplement that in your language of choice which is Python

**Comment by barneygale** [comment]
See https://quarry.readthedocs.io/en/latest/data_types/chunks.html
