### ISSUE TITLE
IndexError when using BlockArray __setitem__

### ISSUE THREAD

**Issue by Epicface92** [barneygale/quarry#66]
When you attempt to set a value in the blockarray, the blockarray will IndexError. I have verified that I pass in a valid id from the global registry and that I send the coordinates in properly.

**Comment by barneygale** [comment]
Can you share the traceback?

**Comment by Epicface92** [comment]
```
File "{omitted}/quarry/types/chunk.py", line 198, in __setitem__
    self.non_air += int(self.registry.is_air_block(self[n])) - \
  File "{omitted}/quarry/types/chunk.py", line 180, in __getitem__
    val = self.data[idx0] >> off0
builtins.IndexError: list index out of range
```

The issue actually occurs in `__getitem__` while `__setitem__` is being called. Would you like me to dump the packet being processed here along w/ the chunk data? I'm doing a project updating chunks inside of a sqlite database.

**Comment by barneygale** [comment]
I think I'm going to re-implement `BlockArray` in C as the bitshift maths is almost impossible to get right in pure Python.

**Comment by barneygale** [comment]
O god it's a huge faff in C too. Now trying a different approach using `bitstring`...

**Comment by barneygale** [comment]
How are you creating your `BlockArray`?

**Comment by Epicface92** [comment]
I'm unpacking the sections from chunk data packets

**Comment by Epicface92** [comment]
prim_bit_mask = column.unpack_varint()

  column.unpack_nbt() # Ignore heightmap

  sections = []

  for i in range(16):

   if prim_bit_mask & (1 << i): # Chunk exists

    sections.append(column.unpack_chunk_section())




  else: # Chunk doesn't exist

   sections.append(BlockArray.empty(column.registry))

**Comment by barneygale** [comment]
Maybe solved in 1cf7e675f057b592fe54db508e9814e6d7fdcaf8 - try the latest master. You'll need to `pip install bitstring`

**Comment by Epicface92** [comment]
```
File "{omitted}/quarry/types/chunk.py", line 218, in __setitem__
    val = BitArray(uint=val, length=self.bits)
  File "{omitted}/bitstring.py", line 3059, in __new__
    y = Bits.__new__(BitArray, auto, length, offset, **kwargs)
  File "{omitted}/bitstring.py", line 812, in __new__
    x._initialise(auto, length, offset, **kwargs)
  File "{omitted}/bitstring.py", line 838, in _initialise
    init_with_length_only[k](self, v, length)
  File "{omitted}/bitstring.py", line 1383, in _setuint
    raise CreationError("A non-zero length must be specified with a "
bitstring.CreationError: A non-zero length must be specified with a uint initialiser.
```

**Comment by barneygale** [comment]
Any chance you can dump the packet and upload it somewhere? `buff.save(); data = buff.read(); buff.restore()` should do the trick. What version of Minecraft are you using?

**Comment by Epicface92** [comment]
Here's a capture of the buffer from the database, note that the file only contains data **after** the chunk Z because I use the chunk X and Z as the key in the database. Let me know if this isn't enough or if there is an issue with this data. My test server is a paper instance running MC 1.14.4

[chunk_example.zip](https://github.com/barneygale/quarry/files/3640378/chunk_example.zip)

**Comment by barneygale** [comment]
Thanks. I've pushed some commits that add a couple handy methods to `Buffer`. Using these I was able to parse the packet as follows:

```
from quarry.types.buffer import Buffer1_14

with open("chunk_example.bin", "rb") as f:
    data = f.read()

buff = Buffer1_14(data)
bitmask = buff.unpack_varint()
heightmap = buff.unpack_nbt()
size = buff.unpack_varint()
sections = buff.unpack_chunk(bitmask)
biomes = buff.unpack('I' * 256)
for _ in range(buff.unpack_varint()):
    be = buff.unpack_nbt()
assert len(buff) == 0
```

Note: the packet also seems to be missing the "Full Chunk" field.

**Comment by Epicface92** [comment]
Thanks, I will test the changes out tomorrow when I get home

**Comment by Epicface92** [comment]
The new chunk parsing functions work great! I've found an issue with setting the block array though. I tried to zero a value in the array, however, the value doesn't change.

**Comment by barneygale** [comment]
Can you share a test case?

**Comment by Epicface92** [comment]
Nevermind, this seems to be an issue with my program. Thanks for the help!
