### ISSUE TITLE
Chunk Format in 1.14

### ISSUE THREAD

**Issue by Nitwel** [barneygale/quarry#69]
Hey, sorry for this odd question, I'm starting to learn how to interpret protocols etc. and struggle on figuring out how the protocol for Chunk Data has changed in version 1.14 compared to older versions. The reason why I need this information is because one of our devs had written a project which manipulates the chunk data send to some clients and due to him not being interested in updating it anymore, I have to figure out what to change so it functions in the version 1.14.

Hope you could give me a bit getting started.
Thanks in advantage. Nitwel

**Comment by barneygale** [comment]
What's the older version?

**Comment by Nitwel** [comment]
Found a forum to get help and forgot to close this issue. (sry)
Have a nice day.  😄
