### ISSUE TITLE
proxy server client forwarding

### ISSUE THREAD

**Issue by mintersqu** [barneygale/quarry#77]
Hello, can I see an example of client forwarding to another local server using a proxy server?

I use this code but it does not work:
`self.connect_host = "localhost"`
`self.connect_port = 25566`
`self.connect()`

I want to redirect the player from the authorization server in the lobby after entering text
But when this code is executed, the player connects to the second server, but does not disconnect from the first, and his just kick because it takes 30 seconds

**Comment by barneygale** [comment]
Could you share your code?
