### ISSUE TITLE
ImportError: No module named dispatch

### ISSUE THREAD

**Issue by shenziro** [barneygale/quarry#8]
Got this Traceback:
```
Traceback (most recent call last):
  File "./mcproxy.py", line 7, in <module>
    from quarry.net.proxy import DownstreamFactory, Bridge
  File "/usr/lib/python2.7/site-packages/quarry/net/proxy.py", line 6, in <module>
    from quarry.util.dispatch import PacketDispatcher
```

I think its broken since the PacketDispatcher was moved to quarry.net in commit bdf65ce053fa3c3882f96ba9c0cc501c40237f1f "Move PacketDispatcher from util to net".

**Comment by barneygale** [comment]
Will fix this evening, sorry about this.

**Comment by barneygale** [comment]
A little delayed, but this should be fixed now. Can you confirm?
