### ISSUE TITLE
I can't start play with this library

### ISSUE THREAD

**Issue by xieyi1393** [barneygale/quarry#82]
I use the Example (ChatRoom Server) and started it.The MOTD and PING is OK,But if I Joined this server ,it through a Excetion:
Internal Exception:io.netty.handler.codec.DecoderException: java.io.IOExcetion:Packet 0/37 (ls) was larger than I Excepted,found 13 bytes extra whilst reading packet 37.(1.14.4)
I add a code on the factory in the Example:
  online_mode = False
Why can't I join the game?

**Comment by xieyi1393** [comment]
I also to try to use 1.12.2,but the same problem occured

**Comment by floflo2607** [comment]
this is not minecraft this just fake a server (u think it's a server but u can't join)

**Comment by recalibrated** [comment]
> this is not minecraft this just fake a server (u think it's a server but u can't join)

Don't think that's how this works lol.
