### ISSUE TITLE
Issues when multithreading

### ISSUE THREAD

**Issue by robgar2001** [barneygale/quarry#87]
Hi, first of all, awesome library!
I did not dive completely into the code yet.
I created a simple multithreading application that connects multiple clients to my private minecraft server. 
I recieve error: reactor already running. This massively limits the amount of client's that can be connected to about 4. Did I just code it wrong? Any way of fixing this, or is this just a limit of the library?

Thanks in advance

**Comment by barneygale** [comment]
Quarry uses `twisted`, which is an event-based framework that can use threading under-the-hood, like Java's netty.
