### ISSUE TITLE
Sending a chunk

### ISSUE THREAD

**Issue by Simetraa** [barneygale/quarry#88]
Hello,

I'm trying to write a very stripped down minecraft server with this library. However, I'm struggling to determine the cause of an error I get when trying to send a chunk to the client. My code so far is adapted from the examples, previous issues (#70) and PyMine's Packets.py (although I could not get that to run either)

`Internal Exception: io.netty.handler.codac.DecoderException: java.io.IOException: Packet 0/34 (nf) was larger than I expected, found 27836 bytes extra whilst reading packet 34.
`
Changing the region file seems to change the number of extra bytes, but not the packet number. The only similar issue I could find was #82, and I don't really understand what the fix was in that case.
```python
x, z = 0, 0
with RegionFile("regionfile3.mca") as f:
    chunk = f.load_chunk(0, 0).body.value["Level"].value
full = chunk["Status"].value == "full"
registry = LookupRegistry.from_json("reports")

sections = [None] * 16
for section in chunk["Sections"].value:
    if 'Palette' in section.value:
        y = section.value["Y"].value
        if 0 <= y < 16:
            blocks = BlockArray.from_nbt(section, registry)
            block_light = None
            sky_light = None
            sections[y] = (blocks, block_light, sky_light)

heightmap = TagRoot.from_body(chunk["Heightmaps"]) # put in tagroot
biomes = chunk["Biomes"].value
block_entities = chunk["TileEntities"].value
sections_data = self.buff_type.pack_chunk(sections)
self.send_packet(
    'chunk_data',
    self.buff_type.pack('ii?', x, z, full), # int, int, bool
    self.buff_type.pack_chunk_bitmask(sections), # [optional?[blockarray]
    self.buff_type.pack_nbt(heightmap),  # TagRoot[TagCompound[TagLongArray[PackedArray]]]
    self.buff_type.pack_array('I', biomes) if full else b'', # []
    # changed in 1.15
    self.buff_type.pack_varint(len(sections_data)), sections_data, #?
    self.buff_type.pack_varint(len(block_entities)), # int
    b''.join(self.buff_type.pack_nbt(entity) for entity in block_entities)) # nbt list

```

**Comment by barneygale** [comment]
Sorrry for the long delay here. Did you still need a hand?

**Comment by Simetraa** [comment]
Yes please, that would be helpful.

**Comment by barneygale** [comment]
Which Minecraft version are you using?

**Comment by ajh123** [comment]
im using 1.16.3 and have the same problem

**Comment by barneygale** [comment]
Will try to work up an example!

**Comment by ajh123** [comment]
@barneygale How far done are. you with the example?

**Comment by TMShader** [comment]
Hey there! Is the example coming long? Or does anyone have a working script?

**Comment by ajh123** [comment]
i dont sadly, seems like no one dose

**Comment by TMShader** [comment]
Soon I'll have one!

**Comment by ajh123** [comment]
@TMShader 
What’s your progress with the example?

**Comment by TMShader** [comment]
@ajh123 
I'm sorry, I forgot to post it, but I can't post it sooner than a week, but as soon as I can I will.
I was trying to make it faster and better, but reading and sending a chunk to a player takes about a second :(
So don't expect some blazing fast code

**Comment by ajh123** [comment]
Thank you!

**Comment by ajh123** [comment]
@TMShader how good and fast is the example now?

**Comment by TMShader** [comment]
@ajh123 I tried generating it from code or reading it from file, but still slow :(
I tried multithreading but nope
I'm not sure what could make it better 
If I can't make it better/faster in a few days I'll extract the code from my testing code and post it here

**Comment by ajh123** [comment]
Thank you!

**Comment by ajh123** [comment]
@TMShader maybe a cache could make it faster for chunks that have not changed and are loaded

**Comment by TMShader** [comment]
@ajh123 i think the packet creation is slow so I could cache the packets maybe... Not sure, I'll try both ways tho, thanks for the help!

**Comment by ajh123** [comment]
@TMShader how much has the cache helped?

**Comment by TMShader** [comment]
@ajh123 I haven't had time to try it yet, but I'll do it as soon as possible

**Comment by ajh123** [comment]
@TMShader will this support 1.17 to

**Comment by TMShader** [comment]
@ajh123 I'm working on that rn but something changed that is not documented on wiki.vg :/

**Comment by ajh123** [comment]
ye, like the 3d biomes and like that

**Comment by ajh123** [comment]
we can look at bukkit / spigot to see how they do it and make it work in python

**Comment by TMShader** [comment]
(And also, 1.17 uses a BitSet instead of a Bitmask)

**Comment by TMShader** [comment]
Ok the example is up, you can find it here @ajh123 https://github.com/TMShader/QuarryMinecraftServerTests

**Comment by ajh123** [comment]
yaaa, now the original issuer (@Simetraa ) needs to try it

**Comment by Simetraa** [comment]
Awesome! I can confirm it works. Thank you very much for your help. A new issue should probably be opened for the 1.17 problem? I'll close this one for now.
![2021-07-27_16 30 50](https://user-images.githubusercontent.com/67224309/127182825-790862cd-da9c-4c37-b456-f0e667d195b3.png)
