### ISSUE TITLE
Automagic PyPi release

### ISSUE THREAD

**Issue by dries007** [barneygale/quarry#90]
@barneygale Could you enter your PyPi credentials in the repo secrets?

Needed: `PYPI_USERNAME` and `PYPI_PASSWORD`.

I would put in my own, but then you'd need to give me permission and admin rights to this repo.

It will allow us to push a build to pypi with every release we make on GitHub.

Here's a step-by-step: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by barneygale** [comment]
Done. I've also granted you 'maintainer' permissions on pypi, if that's any use.

Thanks very much for putting this together.

**Comment by dries007** [comment]
Ok, I'm gonna make a release and see what happens :P

**Comment by dries007** [comment]
Victory! :fireworks:
- https://github.com/barneygale/quarry/actions/runs/154276132
- https://pypi.org/project/quarry/#history
