### ISSUE TITLE
World Generation and Loading

### ISSUE THREAD

**Issue by ExhaustedBiped** [barneygale/quarry#95]
I've got a barebones server running. It loads in, supports chat and a playerlist, and floats the player at 0, 75, 0. How would I load in a pre-generated world or generate one from scratch?

**Comment by barneygale** [comment]
You can load a pre-generated world using `RegionFile` and `BlockArray`. You can send chunks to a player with a [`chunk_data` packet](https://wiki.vg/Protocol#Chunk_Data). Knowing which chunks to send is pretty fiddly, I'd suggest using a proxy (which you can build with quarry!) to check what the official server behaviour is.

As for world generation, that's a bit outside the scope of this project :-). A good start would be some multi-layered perlin noise.
